version: '3'
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=blogs_api
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /home/$USER/mysql/blog_db:/var/lib/mysql
    networks:
      - backend_blog_api
    healthcheck:
      test: ["CMD", "mysql", "-u", "$MYSQL_USER", "-p$MYSQL_PASSWORD", "-e", "SELECT 1"]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 15s
  backend:
    depends_on:
      db:
        condition: service_healthy
    build: .
    restart: unless-stopped
    environment:
      - PORT=3000
      - HOSTNAME=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - API_PATH=${API_PATH}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - ${API_PORT}:3000
    links:
      - db
    networks:
      - backend_blog_api
networks:
  backend_blog_api:
    driver: bridge 